DO $$ BEGIN
 CREATE TYPE "public"."listing_status" AS ENUM('available', 'fully_booked');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "titipinaja_listing" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "titipinaja_listing_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"baggage" integer,
	"price" integer,
	"last_receive_at" varchar(256),
	"departure_at" varchar(256),
	"arrive_at" varchar(256),
	"terms_and_conditions" varchar,
	"listing_status" "listing_status" DEFAULT 'available',
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "titipinaja_password_reset_token" (
	"token_hash" varchar(255),
	"user" varchar(255) NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	CONSTRAINT "titipinaja_password_reset_token_token_hash_unique" UNIQUE("token_hash")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "titipinaja_session" (
	"session_token" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"expires_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "titipinaja_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"username" varchar,
	"hashed_password" varchar,
	"image" varchar(255),
	"email" varchar(255) NOT NULL,
	"email_verified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"session" varchar,
	"picture" varchar(255)
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "titipinaja_user" ADD CONSTRAINT "titipinaja_user_session_titipinaja_session_session_token_fk" FOREIGN KEY ("session") REFERENCES "public"."titipinaja_session"("session_token") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "session_user_id_idx" ON "titipinaja_session" USING btree ("user_id");